#!/usr/bin/env bash
# ================================================================
# scripts/tests/test-wsl-ip-detection.sh
#
# Unit tests for scripts/lib/detect-wsl-ip.sh
#
# Strategy
# --------
# detect_wsl_windows_ip() relies on two external inputs:
#   1. `ip route show` output   → intercepted by prepending a temp
#      directory with a fake `ip` script to PATH.
#   2. /etc/resolv.conf content → intercepted via _WSL_RESOLV_CONF
#      env var pointing at a temp file.
#
# No real network access, no real routing table is touched.
#
# Usage:
#   bash scripts/tests/test-wsl-ip-detection.sh
# ================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LIB="${PROJECT_ROOT}/scripts/lib/detect-wsl-ip.sh"

# ── Counters ──────────────────────────────────────────────────
PASS=0
FAIL=0
ERRORS=()

# ── Colour helpers ────────────────────────────────────────────
GREEN='\033[0;32m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
ok()  { echo -e "  ${GREEN}✓${NC} $*"; }
fail(){ echo -e "  ${RED}✗${NC} $*"; }

# ── Test infrastructure ───────────────────────────────────────

# assert_eq LABEL ACTUAL EXPECTED
assert_eq() {
    local label="$1" actual="$2" expected="$3"
    if [ "$actual" = "$expected" ]; then
        ok "$label"
        PASS=$((PASS + 1))
    else
        fail "$label  →  got='${actual}'  want='${expected}'"
        FAIL=$((FAIL + 1))
        ERRORS+=("$label")
    fi
}

# assert_fails LABEL CMD
# Asserts that CMD exits non-zero.
assert_fails() {
    local label="$1"; shift
    if ! "$@" >/dev/null 2>&1; then
        ok "$label"
        PASS=$((PASS + 1))
    else
        fail "$label  (expected non-zero exit)"
        FAIL=$((FAIL + 1))
        ERRORS+=("$label")
    fi
}

# run_detect [extra env vars...]
# Runs detect_wsl_windows_ip in a clean subshell that:
#   - prepends MOCK_BIN_DIR to PATH (so fake `ip` is used)
#   - sets  _WSL_RESOLV_CONF to MOCK_RESOLV
# Returns the detected IP (stdout) and the exit code.
run_detect() {
    (
        export PATH="${MOCK_BIN_DIR}:${PATH}"
        export _WSL_RESOLV_CONF="${MOCK_RESOLV}"
        # shellcheck source=scripts/lib/detect-wsl-ip.sh
        source "$LIB"
        detect_wsl_windows_ip
    )
}

# ── Fixture helpers ───────────────────────────────────────────
TMPDIR_ROOT=$(mktemp -d)
trap 'rm -rf "$TMPDIR_ROOT"' EXIT

MOCK_BIN_DIR="${TMPDIR_ROOT}/bin"
MOCK_RESOLV="${TMPDIR_ROOT}/resolv.conf"
mkdir -p "$MOCK_BIN_DIR"

# write_ip_routes CONTENT
# Creates a fake `ip` command that prints CONTENT when called as `ip route show`.
write_ip_routes() {
    local content="$1"
    cat > "${MOCK_BIN_DIR}/ip" <<EOF
#!/bin/bash
# Mock ip command for WSL IP detection tests
if [[ "\$*" == "route show" ]]; then
    cat <<'ROUTES'
${content}
ROUTES
fi
EOF
    chmod +x "${MOCK_BIN_DIR}/ip"
}

# write_resolv NAMESERVER_IP
write_resolv() {
    printf "# Generated by resolvconf\nnameserver %s\n" "$1" > "$MOCK_RESOLV"
}

# empty_resolv  — /etc/resolv.conf exists but has no nameserver line
empty_resolv() {
    printf "# Generated by resolvconf\n" > "$MOCK_RESOLV"
}

# no_resolv — resolv.conf does not exist
no_resolv() {
    rm -f "$MOCK_RESOLV"
}

# ================================================================
echo ""
echo -e "${BOLD}WSL Windows-IP Detection — Unit Tests${NC}"
echo "  lib: ${LIB}"
echo ""

# ── Test 1 ───────────────────────────────────────────────────
# Standard WSL2 (no Docker): eth0 route present.
# Expected: use the eth0 gateway (172.22.176.1).
echo "Scenario 1: plain WSL2 — eth0 route present"
write_ip_routes "default via 172.22.176.1 dev eth0 proto kernel"
write_resolv "172.22.176.1"   # resolv.conf agrees, but eth0 should win regardless

result=$(run_detect)
assert_eq "picks eth0 gateway" "$result" "172.22.176.1"

# ── Test 2 ───────────────────────────────────────────────────
# Docker inside WSL rewrites resolv.conf to 172.17.192.1.
# eth0 route still points at the real Windows host (172.22.176.1).
# Expected: eth0 gateway takes priority over resolv.conf.
echo ""
echo "Scenario 2: Docker inside WSL — eth0 wins over rewritten resolv.conf"
write_ip_routes "default via 172.17.192.1 dev docker0 proto kernel
default via 172.22.176.1 dev eth0 proto kernel metric 100"
write_resolv "172.17.192.1"   # Docker's DNS overwrote resolv.conf

result=$(run_detect)
assert_eq "eth0 beats Docker resolv.conf" "$result" "172.22.176.1"

# ── Test 3 ───────────────────────────────────────────────────
# No eth0 route (unusual config), but resolv.conf has the right IP.
# Expected: fall back to resolv.conf.
echo ""
echo "Scenario 3: no eth0 route — falls back to /etc/resolv.conf"
write_ip_routes "default via 10.0.2.2 dev enp0s3 proto dhcp"  # no eth0
write_resolv "10.0.2.2"

result=$(run_detect)
assert_eq "uses resolv.conf when no eth0" "$result" "10.0.2.2"

# ── Test 4 ───────────────────────────────────────────────────
# No eth0 route, no resolv.conf nameserver, but there is another default route.
# Expected: fall back to any default gateway.
echo ""
echo "Scenario 4: no eth0, no resolv.conf nameserver — uses any default route"
write_ip_routes "default via 192.168.50.1 dev wlan0 proto dhcp"
empty_resolv

result=$(run_detect)
assert_eq "last-resort any default gateway" "$result" "192.168.50.1"

# ── Test 5 ───────────────────────────────────────────────────
# Absolutely nothing: no routes, no resolv.conf.
# Expected: function exits non-zero (caller must handle).
echo ""
echo "Scenario 5: no routes, no resolv.conf — returns exit 1"
write_ip_routes ""   # ip route show returns empty output
no_resolv

assert_fails "exits 1 when nothing found" run_detect

# ── Test 6 ───────────────────────────────────────────────────
# Docker route on docker0 but eth0 not present; resolv.conf is absent.
# Expected: falls back to the docker0 default gateway (last resort).
echo ""
echo "Scenario 6: only Docker route, no eth0, no resolv.conf — last-resort Docker GW"
write_ip_routes "default via 172.17.0.1 dev docker0 proto kernel"
no_resolv

result=$(run_detect)
assert_eq "uses docker gw as last resort" "$result" "172.17.0.1"

# ── Test 7 ───────────────────────────────────────────────────
# Multiple eth0 default routes (shouldn't happen but be defensive).
# Expected: first eth0 gateway wins.
echo ""
echo "Scenario 7: two eth0 default routes — picks the first one"
write_ip_routes "default via 172.22.176.1 dev eth0 proto kernel metric 100
default via 172.22.176.2 dev eth0 proto kernel metric 200"
write_resolv "172.22.176.1"

result=$(run_detect)
assert_eq "first eth0 route wins" "$result" "172.22.176.1"

# ── Test 8 ───────────────────────────────────────────────────
# Mirrored networking mode: no separate eth0 gateway, resolv.conf has
# loopback-ish address (127.0.0.1). Verify we still return what resolv.conf says.
echo ""
echo "Scenario 8: mirrored-networking style — resolv.conf = 127.0.0.1"
write_ip_routes ""   # no default routes in mirrored mode
write_resolv "127.0.0.1"

result=$(run_detect)
assert_eq "returns resolv.conf ip in mirrored mode" "$result" "127.0.0.1"

# ── Summary ───────────────────────────────────────────────────
echo ""
echo -e "${BOLD}────────────────────────────────────────${NC}"
TOTAL=$((PASS + FAIL))
echo -e "  Results: ${GREEN}${PASS}${NC} passed, ${RED}${FAIL}${NC} failed  (${TOTAL} total)"

if [ ${#ERRORS[@]} -gt 0 ]; then
    echo ""
    echo -e "  ${RED}Failed tests:${NC}"
    for e in "${ERRORS[@]}"; do
        echo "    - $e"
    done
    echo ""
    exit 1
fi

echo ""
exit 0
